version: '2'
services:
  app:
    image: openjdk:8-jdk-alpine
    ports:
      - "8086:8080"
    working_dir: /usr/src/app
    command: java -jar app.jar
    networks:
      - spring-cloud-network    
    depends_on:
      - mypostgres
      - redis-server
      - rabbitmq-server
      - config-server
    volumes:
      - ./spring-boot-sample/target:/usr/src/app
  config-server:
    image: openjdk:8-jdk-alpine
    working_dir: /usr/src/app
    command: java -jar app.jar
    volumes:
      - ./spring-config-server/target:/usr/src/app
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network
  email-sender:
    image: openjdk:8-jdk-alpine
    working_dir: /usr/src/app
    command: java -jar app.jar    
    ports:
      - "8082:8081"
    networks:
      - spring-cloud-network
    depends_on:
      - rabbitmq-server    
      - config-server 
    volumes:
      - ./spring-rabbitmq-consumer/target:/usr/src/app
  mypostgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring-boot-sample
  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network     
  rabbitmq-server:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    networks:
      - spring-cloud-network          
networks:
  spring-cloud-network:
    driver: bridge     
