version: '3'
services:
  app:
    image: openjdk:8-jdk-alpine
    ports:
      - "8086:8080"
    working_dir: /usr/src/app
    command: java -jar app.jar
    depends_on:
      - mypostgres
      - redis-server
      - rabbitmq-server
      - config-server
    volumes:
      - ./spring-boot-sample/target:/usr/src/app
  config-server:
    image: openjdk:8-jdk-alpine
    working_dir: /usr/src/app
    command: java -jar app.jar
    volumes:
      - ./spring-config-server/target:/usr/src/app
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888"]
      interval: 30s
      timeout: 10s
      retries: 5      
  email-sender:
    image: openjdk:8-jdk-alpine
    working_dir: /usr/src/app
    command: java -jar app.jar    
    ports:
      - "8082:8081"
    depends_on:
      - rabbitmq-server
      - config-server
    volumes:
      - ./spring-rabbitmq-consumer/target:/usr/src/app
  mypostgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring-boot-sample
    volumes:
      - ./migrations:/opt/postgres
    command: psql -U postgres postgres -f /opt/postgres/bootstrap.sql
  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq-server:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
