version: '2'
services:
  app:
    image: java-app
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network    
    depends_on:
      - mypostgres
      - redis-server
      - rabbitmq-server
      - config-server
    volumes:
      - ./spring-boot-sample/target:/opt
  config-server:
    image: java-app
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network
    volumes:
      - ./spring-config-server/target:/opt
  email-sender:
    image: java-app
    ports:
      - "8082:8081"
    networks:
      - spring-cloud-network
    depends_on:
      - rabbitmq-server    
      - config-server 
    volumes:
      - ./spring-rabbitmq-consumer/target:/opt
  mypostgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring-boot-sample
  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network     
  rabbitmq-server:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    networks:
      - spring-cloud-network          
networks:
  spring-cloud-network:
    driver: bridge     
